version: "3.8"

services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: mysql_music_container
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "musicStreamingDb"
    ports:
      - "3308:3306"
    volumes:
      - mysql_data_final:/var/lib/mysql

volumes:
  mysql_data_final:
